// Bank Account Action Types
export const RECEIVE_BANKACCOUNTS = 'RECEIVE_BANKACCOUNTS';
export const FETCH_BANKACCOUNTS = 'FETCH_BANKACCOUNTS';
export const FETCH_BANKACCOUNTS_SUCCESS = 'FETCH_BANKACCOUNTS_SUCCESS';
export const FETCH_BANKACCOUNTS_FAILURE = 'FETCH_BANKACCOUNTS_FAILURE';

// Credt Card Action Types
export const RECEIVE_CREDITCARDS = 'RECEIVE_CREDITCARDS';
export const FETCH_CREDITCARDS = 'FETCH_CREDITCARDS';

// Transaction Action Types
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';